export enum UserActionType {
	GET_ALL_REQUEST = 'GET_ALL_REQUEST',
	GET_ALL_SUCCESS = 'GET_ALL_SUCCESS',
	GET_ALL_FAILED = 'GET_ALL_FAILED',

	GET_BY_ID_REQUEST = 'GET_BY_ID_REQUEST',
	GET_BY_ID_SUCCESS = 'GET_BY_ID_SUCCESS',
	GET_BY_ID_FAILED = 'GET_BY_ID_FAILED'
}
